Public Class Table

    Public Shared Function BuatTablePelayananResep(Optional ByVal NamaTabel As String = "Tabel1") As DataSet
        Dim dsPelayanan As DataSet = New DataSet
        Dim dtPelayanan As DataTable = New DataTable(NamaTabel)
        Dim no_permintaan_obat As New DataColumn("no_permintaan_obat")
        Dim nama_obat_permintaan As New DataColumn("nama_obat_permintaan")
        Dim jml_obat_permintaan As New DataColumn("jml_obat_permintaan")
        Dim status_obat As New DataColumn("status_obat")
        Try
            no_permintaan_obat.DataType = GetType(String)
            nama_obat_permintaan.DataType = GetType(String)
            jml_obat_permintaan.DataType = GetType(Decimal)
            status_obat.DataType = GetType(String)
            With dsPelayanan
                .Tables.Add(dtPelayanan)
                .Tables(0).Columns.Add(no_permintaan_obat)
                .Tables(0).Columns.Add(nama_obat_permintaan)
                .Tables(0).Columns.Add(jml_obat_permintaan)
                .Tables(0).Columns.Add(status_obat)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsPelayanan
    End Function

    Public Shared Function BuatTabelPermintaanObat(Optional ByVal TabelPermintaanObat As String = "TabelPermintaanObat") As DataSet
        Dim dsPermintaanObat As DataSet = New DataSet
        Dim dtPermintaanObat As DataTable = New DataTable(TabelPermintaanObat)
        Dim no_permintaan_obat As New DataColumn("no_permintaan_obat")
        Dim no_reg As New DataColumn("no_reg")
        Dim tanggal_permintaan As New DataColumn("tanggal_permintaan")
        Dim nama_dokter As New DataColumn("nama_dokter")
        Dim nama_pasien As New DataColumn("nama_pasien")
        Dim status As New DataColumn("status")
        Dim status_iteration As New DataColumn("status_iteration")
        Dim iteration_total As New DataColumn("iteration_total")
        Dim iteration_terlayani As New DataColumn("iteration_terlayani")
        Try
            no_permintaan_obat.DataType = GetType(String)
            no_reg.DataType = GetType(String)
            tanggal_permintaan.DataType = GetType(Date)
            nama_dokter.DataType = GetType(String)
            nama_pasien.DataType = GetType(String)
            status.DataType = GetType(String)
            status_iteration.DataType = GetType(String)
            iteration_total.DataType = GetType(Integer)
            iteration_terlayani.DataType = GetType(Integer)
            With dsPermintaanObat
                .Tables.Add(dtPermintaanObat)
                .Tables(0).Columns.Add(no_permintaan_obat)
                .Tables(0).Columns.Add(no_reg)
                .Tables(0).Columns.Add(tanggal_permintaan)
                .Tables(0).Columns.Add(nama_dokter)
                .Tables(0).Columns.Add(nama_pasien)
                .Tables(0).Columns.Add(status)
                .Tables(0).Columns.Add(status_iteration)
                .Tables(0).Columns.Add(iteration_total)
                .Tables(0).Columns.Add(iteration_terlayani)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsPermintaanObat
    End Function

    Public Shared Function BuatTabelPermintaanObatRacikDetail(Optional ByVal TabelPermintaanObatRacikDetail As String = "TabelObatRacikDetail") As DataSet
        Dim dsPermintaanObatRacik As DataSet = New DataSet
        Dim dtPermintaanObatRacik As DataTable = New DataTable(TabelPermintaanObatRacikDetail)
        Dim idx_no_racikan As New DataColumn("idx_no_racikan")
        Dim no_permintaan_obat As New DataColumn("no_permintaan_obat")
        Dim nama_racikan As New DataColumn("nama_racikan")
        Dim kode_barang As New DataColumn("kode_barang")
        Dim nama_barang As New DataColumn("nama_barang")
        Dim jumlah_permintaan As New DataColumn("jumlah_permintaan")
        Dim jumlah_bungkus As New DataColumn("jumlah_bungkus")
        Dim kekuatan As New DataColumn("kekuatan")
        Dim dosis As New DataColumn("dosis")
        Dim waktu As New DataColumn("waktu")
        Dim jenis_racikan As New DataColumn("jenis_racikan")
        Dim signa As New DataColumn("signa")
        Dim ket_minum As New DataColumn("ket_minum")
        Dim status_terlayani As New DataColumn("status_terlayani")
        Dim jumlah_terlayani As New DataColumn("jumlah_terlayani")
        Dim kd_barang_terlayani As New DataColumn("kd_barang_terlayani")
        Dim barang_terlayani As New DataColumn("barang_terlayani")
        Dim no_urut_racikan As New DataColumn("no_urut_racikan")
        Dim keterangan As New DataColumn("keterangan")
        Try
            idx_no_racikan.DataType = GetType(Integer)
            no_permintaan_obat.DataType = GetType(String)
            nama_racikan.DataType = GetType(String)
            kode_barang.DataType = GetType(String)
            nama_barang.DataType = GetType(String)
            jumlah_permintaan.DataType = GetType(Decimal)
            jumlah_bungkus.DataType = GetType(Decimal)
            kekuatan.DataType = GetType(Decimal)
            dosis.DataType = GetType(Decimal)
            waktu.DataType = GetType(String)
            jenis_racikan.DataType = GetType(String)
            signa.DataType = GetType(String)
            ket_minum.DataType = GetType(String)
            keterangan.DataType = GetType(String)
            status_terlayani.DataType = GetType(String)
            jumlah_terlayani.DataType = GetType(Decimal)
            kd_barang_terlayani.DataType = GetType(String)
            barang_terlayani.DataType = GetType(String)
            no_urut_racikan.DataType = GetType(Integer)
            With dsPermintaanObatRacik
                .Tables.Add(dtPermintaanObatRacik)
                .Tables(0).Columns.Add(nama_racikan)
                .Tables(0).Columns.Add(kode_barang)
                .Tables(0).Columns.Add(nama_barang)
                .Tables(0).Columns.Add(jumlah_permintaan)
                .Tables(0).Columns.Add(jumlah_bungkus)
                .Tables(0).Columns.Add(kekuatan)
                .Tables(0).Columns.Add(dosis)
                .Tables(0).Columns.Add(waktu)
                .Tables(0).Columns.Add(jenis_racikan)
                .Tables(0).Columns.Add(signa)
                .Tables(0).Columns.Add(ket_minum)
                .Tables(0).Columns.Add(keterangan)
                .Tables(0).Columns.Add(status_terlayani)
                .Tables(0).Columns.Add(jumlah_terlayani)
                .Tables(0).Columns.Add(kd_barang_terlayani)
                .Tables(0).Columns.Add(barang_terlayani)
                .Tables(0).Columns.Add(no_permintaan_obat)
                .Tables(0).Columns.Add(idx_no_racikan)
                .Tables(0).Columns.Add(no_urut_racikan)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsPermintaanObatRacik
    End Function

    Public Shared Function BuatTabelPermintaanObatDetail(Optional ByVal TabelPermintaanObatDetail As String = "TabelObatDetail") As DataSet
        Dim dsPermintaanObatDetail As DataSet = New DataSet
        Dim dtPermintaanObatDetail As DataTable = New DataTable(TabelPermintaanObatDetail)
        Dim idx_permintaan_obat As New DataColumn("idx_permintaan_obat")
        Dim no_permintaan_obat As New DataColumn("no_permintaan_obat")
        Dim kode_barang As New DataColumn("kode_barang")
        Dim nama_barang As New DataColumn("nama_barang")
        Dim jumlah_permintaan As New DataColumn("jumlah_permintaan")
        Dim takaran As New DataColumn("takaran")
        Dim ket_minum As New DataColumn("ket_minum")
        Dim waktu As New DataColumn("waktu")
        Dim signa As New DataColumn("signa")
        Dim status_terlayani As New DataColumn("status_terlayani")
        Dim jumlah_terlayani As New DataColumn("jumlah_terlayani")
        Dim kd_barang_terlayani As New DataColumn("kd_barang_terlayani")
        Dim barang_terlayani As New DataColumn("barang_terlayani")
        Dim keterangan As New DataColumn("keterangan")
        Try
            idx_permintaan_obat.DataType = GetType(Integer)
            no_permintaan_obat.DataType = GetType(String)
            kode_barang.DataType = GetType(String)
            nama_barang.DataType = GetType(String)
            jumlah_permintaan.DataType = GetType(Decimal)
            takaran.DataType = GetType(String)
            ket_minum.DataType = GetType(String)
            keterangan.DataType = GetType(String)
            waktu.DataType = GetType(String)
            signa.DataType = GetType(String)
            status_terlayani.DataType = GetType(String)
            jumlah_terlayani.DataType = GetType(Decimal)
            kd_barang_terlayani.DataType = GetType(String)
            barang_terlayani.DataType = GetType(String)
            With dsPermintaanObatDetail
                .Tables.Add(dtPermintaanObatDetail)
                .Tables(0).Columns.Add(kode_barang)
                .Tables(0).Columns.Add(nama_barang)
                .Tables(0).Columns.Add(jumlah_permintaan)
                .Tables(0).Columns.Add(signa)
                .Tables(0).Columns.Add(takaran)
                .Tables(0).Columns.Add(waktu)
                .Tables(0).Columns.Add(ket_minum)
                .Tables(0).Columns.Add(keterangan)
                .Tables(0).Columns.Add(status_terlayani)
                .Tables(0).Columns.Add(jumlah_terlayani)
                .Tables(0).Columns.Add(kd_barang_terlayani)
                .Tables(0).Columns.Add(barang_terlayani)
                .Tables(0).Columns.Add(no_permintaan_obat)
                .Tables(0).Columns.Add(idx_permintaan_obat)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsPermintaanObatDetail
    End Function

    Public Shared Function BuatTabelPenjualanResep(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsJual As DataSet = New DataSet
        Dim dtJual As DataTable = New DataTable(NamaTabel)
        Dim urut As New DataColumn("urut")
        Dim racik As New DataColumn("racik")
        Dim nama_barang As New DataColumn("nama_barang")
        Dim harga As New DataColumn("harga")
        Dim jml As New DataColumn("jml")
        Dim nmsatuan As New DataColumn("nmsatuan")
        Dim dijamin As New DataColumn("dijamin")
        Dim sisabayar As New DataColumn("sisabayar")
        Dim jmljatah As New DataColumn("jmljatah")
        Dim stsrawat As New DataColumn("stsrawat")
        Dim kdkasir As New DataColumn("kdkasir")
        Dim nmkasir As New DataColumn("nmkasir")
        Dim tanggal As New DataColumn("tanggal")
        Dim notaresep As New DataColumn("notaresep")
        Dim no_reg As New DataColumn("no_reg")
        Dim no_rm As New DataColumn("no_rm")
        Dim nmpasien As New DataColumn("nmpasien")
        Dim umurthn As New DataColumn("umurthn")
        Dim umurbln As New DataColumn("umurbln")
        Dim kd_penjamin As New DataColumn("kd_penjamin")
        Dim nm_penjamin As New DataColumn("nm_penjamin")
        Dim kddokter As New DataColumn("kddokter")
        Dim nmdokter As New DataColumn("nmdokter")
        Dim nonota As New DataColumn("nonota")
        Dim kd_barang As New DataColumn("kd_barang")
        Dim idx_barang As New DataColumn("idx_barang")
        Dim kd_jns_obat As New DataColumn("kd_jns_obat")
        Dim kd_gol_obat As New DataColumn("kd_gol_obat")
        Dim kd_kel_obat As New DataColumn("kd_kel_obat")
        Dim kdpabrik As New DataColumn("kdpabrik")
        Dim generik As New DataColumn("generik")
        Dim formularium As New DataColumn("formularium")
        Dim jmlp As New DataColumn("jmlp")
        Dim totalp As New DataColumn("totalp")
        Dim jmln As New DataColumn("jmln")
        Dim totaln As New DataColumn("totaln")
        Dim totalharga As New DataColumn("totalharga")
        Dim senpot As New DataColumn("senpot")
        Dim potongan As New DataColumn("potongan")
        Dim jmlnet As New DataColumn("jmlnet")
        Dim hrgbeli As New DataColumn("hrgbeli")
        Dim jamawal As New DataColumn("jamawal")
        Dim kdbagian As New DataColumn("kdbagian")
        Dim stsresep As New DataColumn("stsresep")
        Dim rek_p As New DataColumn("rek_p")
        Dim stsetiket As New DataColumn("stsetiket")
        Dim qty1 As New DataColumn("qty1")
        Dim qty2 As New DataColumn("qty2")
        Dim qty3 As New DataColumn("qty3")
        Dim jmlhari As New DataColumn("jmlhari")
        Dim takaran As New DataColumn("takaran")
        Dim waktu As New DataColumn("waktu")
        Dim ketminum As New DataColumn("ketminum")
        Dim posting As New DataColumn("posting")
        Dim diserahkan As New DataColumn("diserahkan")
        Dim jns_obat As New DataColumn("jns_obat")
        Dim tglakhir As New DataColumn("tglakhir")
        Dim jml_awal As New DataColumn("jml_awal")
        Dim tgl_exp As New DataColumn("tgl_exp")
        Dim nmobat_etiket As New DataColumn("nmobat_etiket")
        Dim jmlobat_etiket As New DataColumn("jmlobat_etiket")
        Dim model_etiket As New DataColumn("model_etiket")
        Dim nmobat_etiket_infus As New DataColumn("nmobat_etiket_infus")
        Dim jmlobat_etiket_infus As New DataColumn("jmlobat_etiket_infus")
        Dim obat_infus As New DataColumn("obat_infus")
        Dim tetes_infus As New DataColumn("tetes_infus")
        Dim ket_waktu_pagi_model4 As New DataColumn("ket_waktu_pagi_model4")
        Dim ket_waktu_siang_model4 As New DataColumn("ket_waktu_siang_model4")
        Dim ket_waktu_sore_model4 As New DataColumn("ket_waktu_sore_model4")
        Dim ket_waktu_malam_model4 As New DataColumn("ket_waktu_malam_model4")
        Dim ket_minum_model4 As New DataColumn("ket_minum_model4")
        Dim takaran_s As New DataColumn("takaran_s")
        Dim waktu_s As New DataColumn("waktu_s")
        Dim ketminum_s As New DataColumn("ketminum_s")
        Try
            urut.DataType = GetType(Integer)
            racik.DataType = GetType(String)
            nama_barang.DataType = GetType(String)
            harga.DataType = GetType(Decimal)
            jmlp.DataType = GetType(Decimal)
            nmsatuan.DataType = GetType(String)
            totalp.DataType = GetType(Decimal)
            stsrawat.DataType = GetType(String)
            kdkasir.DataType = GetType(String)
            nmkasir.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            notaresep.DataType = GetType(String)
            no_reg.DataType = GetType(String)
            no_rm.DataType = GetType(String)
            nmpasien.DataType = GetType(String)
            umurthn.DataType = GetType(Integer)
            umurbln.DataType = GetType(Integer)
            kd_penjamin.DataType = GetType(String)
            nm_penjamin.DataType = GetType(String)
            kddokter.DataType = GetType(String)
            nmdokter.DataType = GetType(String)
            nonota.DataType = GetType(String)
            jml.DataType = GetType(Decimal)
            kd_barang.DataType = GetType(String)
            idx_barang.DataType = GetType(Integer)
            kd_jns_obat.DataType = GetType(Integer)
            kd_gol_obat.DataType = GetType(Integer)
            kd_kel_obat.DataType = GetType(Integer)
            kdpabrik.DataType = GetType(String)
            generik.DataType = GetType(String)
            formularium.DataType = GetType(String)
            jmln.DataType = GetType(Decimal)
            totaln.DataType = GetType(Decimal)
            totalharga.DataType = GetType(Decimal)
            senpot.DataType = GetType(Decimal)
            potongan.DataType = GetType(Decimal)
            jmlnet.DataType = GetType(Decimal)
            dijamin.DataType = GetType(Decimal)
            sisabayar.DataType = GetType(Decimal)
            hrgbeli.DataType = GetType(Decimal)
            jamawal.DataType = GetType(String)
            kdbagian.DataType = GetType(String)
            stsresep.DataType = GetType(String)
            rek_p.DataType = GetType(String)
            stsetiket.DataType = GetType(String)
            qty1.DataType = GetType(String)
            qty2.DataType = GetType(String)
            qty3.DataType = GetType(String)
            jmlhari.DataType = GetType(Integer)
            takaran.DataType = GetType(Integer)
            waktu.DataType = GetType(Integer)
            ketminum.DataType = GetType(Integer)
            posting.DataType = GetType(String)
            diserahkan.DataType = GetType(String)
            jns_obat.DataType = GetType(String)
            jmljatah.DataType = GetType(Integer)
            tglakhir.DataType = GetType(DateTime)
            jml_awal.DataType = GetType(Decimal)
            tgl_exp.DataType = GetType(DateTime)
            nmobat_etiket.DataType = GetType(String)
            jmlobat_etiket.DataType = GetType(Decimal)
            model_etiket.DataType = GetType(String)
            nmobat_etiket_infus.DataType = GetType(String)
            jmlobat_etiket_infus.DataType = GetType(Decimal)
            obat_infus.DataType = GetType(String)
            tetes_infus.DataType = GetType(String)
            ket_waktu_pagi_model4.DataType = GetType(String)
            ket_waktu_siang_model4.DataType = GetType(String)
            ket_waktu_sore_model4.DataType = GetType(String)
            ket_waktu_malam_model4.DataType = GetType(String)
            ket_minum_model4.DataType = GetType(String)
            takaran_s.DataType = GetType(String)
            waktu_s.DataType = GetType(String)
            ketminum_s.DataType = GetType(String)
            With dsJual
                .Tables.Add(dtJual)
                .Tables(0).Columns.Add(urut)
                .Tables(0).Columns.Add(racik)
                .Tables(0).Columns.Add(nama_barang)
                .Tables(0).Columns.Add(harga)
                .Tables(0).Columns.Add(jml)
                .Tables(0).Columns.Add(nmsatuan)
                .Tables(0).Columns.Add(totalharga)
                .Tables(0).Columns.Add(dijamin)
                .Tables(0).Columns.Add(sisabayar)
                .Tables(0).Columns.Add(jmljatah)
                .Tables(0).Columns.Add(stsrawat)
                .Tables(0).Columns.Add(kdkasir)
                .Tables(0).Columns.Add(nmkasir)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(notaresep)
                .Tables(0).Columns.Add(no_reg)
                .Tables(0).Columns.Add(no_rm)
                .Tables(0).Columns.Add(nmpasien)
                .Tables(0).Columns.Add(umurthn)
                .Tables(0).Columns.Add(umurbln)
                .Tables(0).Columns.Add(kd_penjamin)
                .Tables(0).Columns.Add(nm_penjamin)
                .Tables(0).Columns.Add(kddokter)
                .Tables(0).Columns.Add(nmdokter)
                .Tables(0).Columns.Add(nonota)
                .Tables(0).Columns.Add(kd_barang)
                .Tables(0).Columns.Add(idx_barang)
                .Tables(0).Columns.Add(kd_jns_obat)
                .Tables(0).Columns.Add(kd_gol_obat)
                .Tables(0).Columns.Add(kd_kel_obat)
                .Tables(0).Columns.Add(kdpabrik)
                .Tables(0).Columns.Add(generik)
                .Tables(0).Columns.Add(formularium)
                .Tables(0).Columns.Add(jmln)
                .Tables(0).Columns.Add(totaln)
                .Tables(0).Columns.Add(jmlp)
                .Tables(0).Columns.Add(totalp)
                .Tables(0).Columns.Add(senpot)
                .Tables(0).Columns.Add(potongan)
                .Tables(0).Columns.Add(jmlnet)
                .Tables(0).Columns.Add(hrgbeli)
                .Tables(0).Columns.Add(jamawal)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(stsresep)
                .Tables(0).Columns.Add(rek_p)
                .Tables(0).Columns.Add(stsetiket)
                .Tables(0).Columns.Add(qty1)
                .Tables(0).Columns.Add(qty2)
                .Tables(0).Columns.Add(qty3)
                .Tables(0).Columns.Add(jmlhari)
                .Tables(0).Columns.Add(takaran)
                .Tables(0).Columns.Add(waktu)
                .Tables(0).Columns.Add(ketminum)
                .Tables(0).Columns.Add(posting)
                .Tables(0).Columns.Add(diserahkan)
                .Tables(0).Columns.Add(jns_obat)
                .Tables(0).Columns.Add(tglakhir)
                .Tables(0).Columns.Add(jml_awal)
                .Tables(0).Columns.Add(tgl_exp)
                .Tables(0).Columns.Add(nmobat_etiket)
                .Tables(0).Columns.Add(jmlobat_etiket)
                .Tables(0).Columns.Add(model_etiket)
                .Tables(0).Columns.Add(nmobat_etiket_infus)
                .Tables(0).Columns.Add(jmlobat_etiket_infus)
                .Tables(0).Columns.Add(obat_infus)
                .Tables(0).Columns.Add(tetes_infus)
                .Tables(0).Columns.Add(ket_waktu_pagi_model4)
                .Tables(0).Columns.Add(ket_waktu_siang_model4)
                .Tables(0).Columns.Add(ket_waktu_sore_model4)
                .Tables(0).Columns.Add(ket_waktu_malam_model4)
                .Tables(0).Columns.Add(ket_minum_model4)
                .Tables(0).Columns.Add(takaran_s)
                .Tables(0).Columns.Add(waktu_s)
                .Tables(0).Columns.Add(ketminum_s)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsJual
    End Function

    Public Shared Function BuatTabelPenjualanResepKh(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsJual As DataSet = New DataSet
        Dim dtJual As DataTable = New DataTable(NamaTabel)
        Dim urut As New DataColumn("urut")
        Dim racik As New DataColumn("racik")
        Dim nama_barang As New DataColumn("nama_barang")
        Dim harga As New DataColumn("harga")
        Dim jml As New DataColumn("jml")
        Dim nmsatuan As New DataColumn("nmsatuan")
        Dim dijamin As New DataColumn("dijamin")
        Dim sisabayar As New DataColumn("sisabayar")
        Dim jmljatah As New DataColumn("jmljatah")
        Dim stsrawat As New DataColumn("stsrawat")
        Dim kdkasir As New DataColumn("kdkasir")
        Dim nmkasir As New DataColumn("nmkasir")
        Dim tanggal As New DataColumn("tanggal")
        Dim notaresep As New DataColumn("notaresep")
        Dim no_reg As New DataColumn("no_reg")
        Dim no_rm As New DataColumn("no_rm")
        Dim nmpasien As New DataColumn("nmpasien")
        Dim umurthn As New DataColumn("umurthn")
        Dim umurbln As New DataColumn("umurbln")
        Dim kd_penjamin As New DataColumn("kd_penjamin")
        Dim nm_penjamin As New DataColumn("nm_penjamin")
        Dim kddokter As New DataColumn("kddokter")
        Dim nmdokter As New DataColumn("nmdokter")
        Dim nonota As New DataColumn("nonota")
        Dim kd_barang As New DataColumn("kd_barang")
        Dim idx_barang As New DataColumn("idx_barang")
        Dim kd_jns_obat As New DataColumn("kd_jns_obat")
        Dim kd_gol_obat As New DataColumn("kd_gol_obat")
        Dim kd_kel_obat As New DataColumn("kd_kel_obat")
        Dim kdpabrik As New DataColumn("kdpabrik")
        Dim generik As New DataColumn("generik")
        Dim formularium As New DataColumn("formularium")
        Dim jmlp As New DataColumn("jmlp")
        Dim totalp As New DataColumn("totalp")
        Dim jmln As New DataColumn("jmln")
        Dim totaln As New DataColumn("totaln")
        Dim totalharga As New DataColumn("totalharga")
        Dim senpot As New DataColumn("senpot")
        Dim potongan As New DataColumn("potongan")
        Dim jmlnet As New DataColumn("jmlnet")
        Dim hrgbeli As New DataColumn("hrgbeli")
        Dim jamawal As New DataColumn("jamawal")
        Dim kdbagian As New DataColumn("kdbagian")
        Dim stsresep As New DataColumn("stsresep")
        Dim rek_p As New DataColumn("rek_p")
        Dim stsetiket As New DataColumn("stsetiket")
        Dim qty1 As New DataColumn("qty1")
        Dim qty2 As New DataColumn("qty2")
        Dim qty3 As New DataColumn("qty3")
        Dim jmlhari As New DataColumn("jmlhari")
        Dim takaran As New DataColumn("takaran")
        Dim waktu As New DataColumn("waktu")
        Dim ketminum As New DataColumn("ketminum")
        Dim posting As New DataColumn("posting")
        Dim diserahkan As New DataColumn("diserahkan")
        Dim jns_obat As New DataColumn("jns_obat")
        Dim tglakhir As New DataColumn("tglakhir")
        Dim jml_awal As New DataColumn("jml_awal")
        Dim tgl_exp As New DataColumn("tgl_exp")
        Dim nmobat_etiket As New DataColumn("nmobat_etiket")
        Dim jmlobat_etiket As New DataColumn("jmlobat_etiket")
        Dim model_etiket As New DataColumn("model_etiket")
        Dim nmobat_etiket_infus As New DataColumn("nmobat_etiket_infus")
        Dim jmlobat_etiket_infus As New DataColumn("jmlobat_etiket_infus")
        Dim obat_infus As New DataColumn("obat_infus")
        Dim tetes_infus As New DataColumn("tetes_infus")
        Dim ket_waktu_pagi_model4 As New DataColumn("ket_waktu_pagi_model4")
        Dim ket_waktu_siang_model4 As New DataColumn("ket_waktu_siang_model4")
        Dim ket_waktu_sore_model4 As New DataColumn("ket_waktu_sore_model4")
        Dim ket_waktu_malam_model4 As New DataColumn("ket_waktu_malam_model4")
        Dim ket_minum_model4 As New DataColumn("ket_minum_model4")
        Dim jenis_model4 As New DataColumn("jenis_model4")
        Dim takaran_s As New DataColumn("takaran_s")
        Dim waktu_s As New DataColumn("waktu_s")
        Dim ketminum_s As New DataColumn("ketminum_s")
        Try
            urut.DataType = GetType(Integer)
            racik.DataType = GetType(String)
            nama_barang.DataType = GetType(String)
            harga.DataType = GetType(Decimal)
            jmlp.DataType = GetType(Decimal)
            nmsatuan.DataType = GetType(String)
            totalp.DataType = GetType(Decimal)
            stsrawat.DataType = GetType(String)
            kdkasir.DataType = GetType(String)
            nmkasir.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            notaresep.DataType = GetType(String)
            no_reg.DataType = GetType(String)
            no_rm.DataType = GetType(String)
            nmpasien.DataType = GetType(String)
            umurthn.DataType = GetType(Integer)
            umurbln.DataType = GetType(Integer)
            kd_penjamin.DataType = GetType(String)
            nm_penjamin.DataType = GetType(String)
            kddokter.DataType = GetType(String)
            nmdokter.DataType = GetType(String)
            nonota.DataType = GetType(String)
            jml.DataType = GetType(Decimal)
            kd_barang.DataType = GetType(String)
            idx_barang.DataType = GetType(Integer)
            kd_jns_obat.DataType = GetType(Integer)
            kd_gol_obat.DataType = GetType(Integer)
            kd_kel_obat.DataType = GetType(Integer)
            kdpabrik.DataType = GetType(String)
            generik.DataType = GetType(String)
            formularium.DataType = GetType(String)
            jmln.DataType = GetType(Decimal)
            totaln.DataType = GetType(Decimal)
            totalharga.DataType = GetType(Decimal)
            senpot.DataType = GetType(Decimal)
            potongan.DataType = GetType(Decimal)
            jmlnet.DataType = GetType(Decimal)
            dijamin.DataType = GetType(Decimal)
            sisabayar.DataType = GetType(Decimal)
            hrgbeli.DataType = GetType(Decimal)
            jamawal.DataType = GetType(String)
            kdbagian.DataType = GetType(String)
            stsresep.DataType = GetType(String)
            rek_p.DataType = GetType(String)
            stsetiket.DataType = GetType(String)
            qty1.DataType = GetType(String)
            qty2.DataType = GetType(String)
            qty3.DataType = GetType(String)
            jmlhari.DataType = GetType(Integer)
            takaran.DataType = GetType(Integer)
            waktu.DataType = GetType(Integer)
            ketminum.DataType = GetType(Integer)
            posting.DataType = GetType(String)
            diserahkan.DataType = GetType(String)
            jns_obat.DataType = GetType(String)
            jmljatah.DataType = GetType(Integer)
            tglakhir.DataType = GetType(DateTime)
            jml_awal.DataType = GetType(Decimal)
            tgl_exp.DataType = GetType(DateTime)
            nmobat_etiket.DataType = GetType(String)
            jmlobat_etiket.DataType = GetType(Decimal)
            model_etiket.DataType = GetType(String)
            nmobat_etiket_infus.DataType = GetType(String)
            jmlobat_etiket_infus.DataType = GetType(Decimal)
            obat_infus.DataType = GetType(String)
            tetes_infus.DataType = GetType(String)
            ket_waktu_pagi_model4.DataType = GetType(String)
            ket_waktu_siang_model4.DataType = GetType(String)
            ket_waktu_sore_model4.DataType = GetType(String)
            ket_waktu_malam_model4.DataType = GetType(String)
            ket_minum_model4.DataType = GetType(String)
            jenis_model4.DataType = GetType(String)
            takaran_s.DataType = GetType(String)
            waktu_s.DataType = GetType(String)
            ketminum_s.DataType = GetType(String)
            With dsJual
                .Tables.Add(dtJual)
                .Tables(0).Columns.Add(urut)
                .Tables(0).Columns.Add(racik)
                .Tables(0).Columns.Add(nama_barang)
                .Tables(0).Columns.Add(harga)
                .Tables(0).Columns.Add(jmlp)
                .Tables(0).Columns.Add(totalp)
                .Tables(0).Columns.Add(jmln)
                .Tables(0).Columns.Add(totaln)
                .Tables(0).Columns.Add(jml)
                .Tables(0).Columns.Add(nmsatuan)
                .Tables(0).Columns.Add(jmljatah)
                .Tables(0).Columns.Add(dijamin)
                .Tables(0).Columns.Add(sisabayar)
                .Tables(0).Columns.Add(stsrawat)
                .Tables(0).Columns.Add(kdkasir)
                .Tables(0).Columns.Add(nmkasir)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(notaresep)
                .Tables(0).Columns.Add(no_reg)
                .Tables(0).Columns.Add(no_rm)
                .Tables(0).Columns.Add(nmpasien)
                .Tables(0).Columns.Add(umurthn)
                .Tables(0).Columns.Add(umurbln)
                .Tables(0).Columns.Add(kd_penjamin)
                .Tables(0).Columns.Add(nm_penjamin)
                .Tables(0).Columns.Add(kddokter)
                .Tables(0).Columns.Add(nmdokter)
                .Tables(0).Columns.Add(nonota)
                .Tables(0).Columns.Add(kd_barang)
                .Tables(0).Columns.Add(idx_barang)
                .Tables(0).Columns.Add(kd_jns_obat)
                .Tables(0).Columns.Add(kd_gol_obat)
                .Tables(0).Columns.Add(kd_kel_obat)
                .Tables(0).Columns.Add(kdpabrik)
                .Tables(0).Columns.Add(generik)
                .Tables(0).Columns.Add(formularium)
                .Tables(0).Columns.Add(totalharga)
                .Tables(0).Columns.Add(senpot)
                .Tables(0).Columns.Add(potongan)
                .Tables(0).Columns.Add(jmlnet)
                .Tables(0).Columns.Add(hrgbeli)
                .Tables(0).Columns.Add(jamawal)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(stsresep)
                .Tables(0).Columns.Add(rek_p)
                .Tables(0).Columns.Add(stsetiket)
                .Tables(0).Columns.Add(qty1)
                .Tables(0).Columns.Add(qty2)
                .Tables(0).Columns.Add(qty3)
                .Tables(0).Columns.Add(jmlhari)
                .Tables(0).Columns.Add(takaran)
                .Tables(0).Columns.Add(waktu)
                .Tables(0).Columns.Add(ketminum)
                .Tables(0).Columns.Add(posting)
                .Tables(0).Columns.Add(diserahkan)
                .Tables(0).Columns.Add(jns_obat)
                .Tables(0).Columns.Add(tglakhir)
                .Tables(0).Columns.Add(jml_awal)
                .Tables(0).Columns.Add(tgl_exp)
                .Tables(0).Columns.Add(nmobat_etiket)
                .Tables(0).Columns.Add(jmlobat_etiket)
                .Tables(0).Columns.Add(model_etiket)
                .Tables(0).Columns.Add(nmobat_etiket_infus)
                .Tables(0).Columns.Add(jmlobat_etiket_infus)
                .Tables(0).Columns.Add(obat_infus)
                .Tables(0).Columns.Add(tetes_infus)
                .Tables(0).Columns.Add(ket_waktu_pagi_model4)
                .Tables(0).Columns.Add(ket_waktu_siang_model4)
                .Tables(0).Columns.Add(ket_waktu_sore_model4)
                .Tables(0).Columns.Add(ket_waktu_malam_model4)
                .Tables(0).Columns.Add(ket_minum_model4)
                .Tables(0).Columns.Add(jenis_model4)
                .Tables(0).Columns.Add(takaran_s)
                .Tables(0).Columns.Add(waktu_s)
                .Tables(0).Columns.Add(ketminum_s)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsJual
    End Function

    Public Shared Function BuatTabelPenjualanNonResep(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsJual As DataSet = New DataSet
        Dim dtJual As DataTable = New DataTable(NamaTabel)
        Dim kdbagian As New DataColumn("kdbagian")
        Dim nmbagian As New DataColumn("nmbagian")
        Dim kdkasir As New DataColumn("kdkasir")
        Dim nmkasir As New DataColumn("nmkasir")
        Dim tanggal As New DataColumn("tanggal")
        Dim nota As New DataColumn("nota")
        Dim kdkons As New DataColumn("kdkons")
        Dim nmkons As New DataColumn("nmkons")
        Dim nama As New DataColumn("nama")
        Dim kddokter As New DataColumn("kddokter")
        Dim nmdokter As New DataColumn("nmdokter")
        Dim urut As New DataColumn("urut")
        Dim idx_barang As New DataColumn("idx_barang")
        Dim kdbarang As New DataColumn("kdbarang")
        Dim nmbarang As New DataColumn("nmbarang")
        Dim kdjenis As New DataColumn("kdjenis")
        Dim nmjenis As New DataColumn("nmjenis")
        Dim kdkel As New DataColumn("kdkel")
        Dim kdgol As New DataColumn("kdgol")
        Dim generik As New DataColumn("generik")
        Dim harga As New DataColumn("harga")
        Dim jml As New DataColumn("jml")
        Dim nmsatuan As New DataColumn("nmsatuan")
        Dim jmltotal As New DataColumn("jmltotal")
        Dim tuslah As New DataColumn("tuslah")
        Dim jmlharga As New DataColumn("jmlharga")
        Dim senpot As New DataColumn("senpot")
        Dim potongan As New DataColumn("potongan")
        Dim jmlnet As New DataColumn("jmlnet")
        Dim posting As New DataColumn("posting")
        Dim diserahkan As New DataColumn("diserahkan")
        Dim hpp As New DataColumn("hpp")
        Dim racik As New DataColumn("racik")
        Dim jmlracik As New DataColumn("jmlracik")
        Dim jml_awal As New DataColumn("jml_awal")
        Dim rek_p As New DataColumn("rek_p")
        Dim stsEtiket As New DataColumn("stsEtiket")
        Dim nmObatEtiket As New DataColumn("nmObatEtiket")
        Dim jmlObatEtiket As New DataColumn("jmlObatEtiket")
        Dim signa1 As New DataColumn("signa1")
        Dim signa2 As New DataColumn("signa2")
        Dim takaranEtiket As New DataColumn("takaranEtiket")
        Dim waktuEtiket As New DataColumn("waktuEtiket")
        Dim ketEtiket As New DataColumn("ketEtiket")
        Dim tglED As New DataColumn("tglED")
        Try
            kdbagian.DataType = GetType(String)
            nmbagian.DataType = GetType(String)
            kdkasir.DataType = GetType(String)
            nmkasir.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            nota.DataType = GetType(String)
            kdkons.DataType = GetType(String)
            nmkons.DataType = GetType(String)
            nama.DataType = GetType(String)
            kddokter.DataType = GetType(String)
            nmdokter.DataType = GetType(String)
            urut.DataType = GetType(Integer)
            idx_barang.DataType = GetType(Integer)
            kdbarang.DataType = GetType(String)
            nmbarang.DataType = GetType(String)
            kdjenis.DataType = GetType(Integer)
            nmjenis.DataType = GetType(String)
            kdkel.DataType = GetType(Integer)
            kdgol.DataType = GetType(Integer)
            generik.DataType = GetType(String)
            harga.DataType = GetType(Decimal)
            jml.DataType = GetType(Decimal)
            nmsatuan.DataType = GetType(String)
            jmltotal.DataType = GetType(Decimal)
            tuslah.DataType = GetType(Decimal)
            jmlharga.DataType = GetType(Decimal)
            senpot.DataType = GetType(Decimal)
            potongan.DataType = GetType(Decimal)
            jmlnet.DataType = GetType(Decimal)
            posting.DataType = GetType(String)
            diserahkan.DataType = GetType(String)
            hpp.DataType = GetType(Decimal)
            racik.DataType = GetType(String)
            jmlracik.DataType = GetType(Decimal)
            jml_awal.DataType = GetType(Decimal)
            rek_p.DataType = GetType(String)
            stsEtiket.DataType = GetType(String)
            nmObatEtiket.DataType = GetType(String)
            jmlObatEtiket.DataType = GetType(Decimal)
            signa1.DataType = GetType(String)
            signa2.DataType = GetType(String)
            takaranEtiket.DataType = GetType(Integer)
            waktuEtiket.DataType = GetType(Integer)
            ketEtiket.DataType = GetType(Integer)
            tglED.DataType = GetType(DateTime)
            With dsJual
                .Tables.Add(dtJual)
                .Tables(0).Columns.Add(urut)
                .Tables(0).Columns.Add(racik)
                .Tables(0).Columns.Add(nmbarang)
                .Tables(0).Columns.Add(harga)
                .Tables(0).Columns.Add(jml)
                .Tables(0).Columns.Add(nmsatuan)
                .Tables(0).Columns.Add(jmlharga)
                .Tables(0).Columns.Add(senpot)
                .Tables(0).Columns.Add(potongan)
                .Tables(0).Columns.Add(jmlnet)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(nmbagian)
                .Tables(0).Columns.Add(kdkasir)
                .Tables(0).Columns.Add(nmkasir)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(nota)
                .Tables(0).Columns.Add(kdkons)
                .Tables(0).Columns.Add(nmkons)
                .Tables(0).Columns.Add(nama)
                .Tables(0).Columns.Add(kddokter)
                .Tables(0).Columns.Add(nmdokter)
                .Tables(0).Columns.Add(idx_barang)
                .Tables(0).Columns.Add(kdbarang)
                .Tables(0).Columns.Add(kdjenis)
                .Tables(0).Columns.Add(nmjenis)
                .Tables(0).Columns.Add(kdkel)
                .Tables(0).Columns.Add(kdgol)
                .Tables(0).Columns.Add(generik)
                .Tables(0).Columns.Add(jmltotal)
                .Tables(0).Columns.Add(tuslah)
                .Tables(0).Columns.Add(posting)
                .Tables(0).Columns.Add(diserahkan)
                .Tables(0).Columns.Add(hpp)
                .Tables(0).Columns.Add(jmlracik)
                .Tables(0).Columns.Add(jml_awal)
                .Tables(0).Columns.Add(rek_p)
                .Tables(0).Columns.Add(stsEtiket)
                .Tables(0).Columns.Add(nmObatEtiket)
                .Tables(0).Columns.Add(jmlObatEtiket)
                .Tables(0).Columns.Add(signa1)
                .Tables(0).Columns.Add(signa2)
                .Tables(0).Columns.Add(takaranEtiket)
                .Tables(0).Columns.Add(waktuEtiket)
                .Tables(0).Columns.Add(ketEtiket)
                .Tables(0).Columns.Add(tglED)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsJual
    End Function

    Public Shared Function BuatTabelReturObatRJ(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsRetur As DataSet = New DataSet
        Dim dtRetur As DataTable = New DataTable(NamaTabel)
        Dim kdkasir As New DataColumn("kdkasir")
        Dim nmkasir As New DataColumn("nmkasir")
        Dim kdbagian As New DataColumn("kdbagian")
        Dim tanggal As New DataColumn("tanggal")
        Dim notaretur As New DataColumn("notaretur")
        Dim no_reg As New DataColumn("no_reg")
        Dim no_rm As New DataColumn("no_rm")
        Dim nmpasien As New DataColumn("nmpasien")
        Dim umurthn As New DataColumn("umurthn")
        Dim umurbln As New DataColumn("umurbln")
        Dim kd_penjamin As New DataColumn("kd_penjamin")
        Dim nm_penjamin As New DataColumn("nm_penjamin")
        Dim urut As New DataColumn("urut")
        Dim noid As New DataColumn("noid")
        Dim kd_barang As New DataColumn("kd_barang")
        Dim idx_barang As New DataColumn("idx_barang")
        Dim nama_barang As New DataColumn("nama_barang")
        Dim generik As New DataColumn("generik")
        Dim kd_jns_obat As New DataColumn("kd_jns_obat")
        Dim kd_gol_obat As New DataColumn("kd_gol_obat")
        Dim kd_kel_obat As New DataColumn("kd_kel_obat")
        Dim kdpabrik As New DataColumn("kdpabrik")
        Dim rek_p As New DataColumn("rek_p")
        Dim formularium As New DataColumn("formularium")
        Dim tglresep As New DataColumn("tglresep")
        Dim notaresep As New DataColumn("notaresep")
        Dim kddokter As New DataColumn("kddokter")
        Dim nmdokter As New DataColumn("nmdokter")
        Dim hrgppn As New DataColumn("hrgppn")
        Dim jmlretpkt As New DataColumn("jmlretpkt")
        Dim jmlretnpkt As New DataColumn("jmlretnpkt")
        Dim totalqty As New DataColumn("totalqty")
        Dim nmsatuan As New DataColumn("nmsatuan")
        Dim jmlhrgpkt As New DataColumn("jmlhrgpkt")
        Dim jmlhrgnpkt As New DataColumn("jmlhrgnpkt")
        Dim jmlhrgret As New DataColumn("jmlhrgret")
        Dim dijamin As New DataColumn("dijamin")
        Dim iurpasien As New DataColumn("iurpasien")
        Dim jns_obat As New DataColumn("jns_obat")

        Try
            kdkasir.DataType = GetType(String)
            nmkasir.DataType = GetType(String)
            kdbagian.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            notaretur.DataType = GetType(String)
            no_reg.DataType = GetType(String)
            no_rm.DataType = GetType(String)
            nmpasien.DataType = GetType(String)
            umurthn.DataType = GetType(Integer)
            umurbln.DataType = GetType(Integer)
            kd_penjamin.DataType = GetType(String)
            nm_penjamin.DataType = GetType(String)
            urut.DataType = GetType(Integer)
            noid.DataType = GetType(Integer)
            kd_barang.DataType = GetType(String)
            idx_barang.DataType = GetType(Integer)
            nama_barang.DataType = GetType(String)
            generik.DataType = GetType(String)
            kd_jns_obat.DataType = GetType(Integer)
            kd_gol_obat.DataType = GetType(Integer)
            kd_kel_obat.DataType = GetType(Integer)
            kdpabrik.DataType = GetType(String)
            rek_p.DataType = GetType(String)
            formularium.DataType = GetType(String)
            tglresep.DataType = GetType(DateTime)
            notaresep.DataType = GetType(String)
            kddokter.DataType = GetType(String)
            nmdokter.DataType = GetType(String)
            hrgppn.DataType = GetType(Decimal)
            jmlretpkt.DataType = GetType(Decimal)
            jmlretnpkt.DataType = GetType(Decimal)
            totalqty.DataType = GetType(Decimal)
            nmsatuan.DataType = GetType(String)
            jmlhrgpkt.DataType = GetType(Decimal)
            jmlhrgnpkt.DataType = GetType(Decimal)
            jmlhrgret.DataType = GetType(Decimal)
            dijamin.DataType = GetType(Decimal)
            iurpasien.DataType = GetType(Decimal)
            jns_obat.DataType = GetType(String)
            With dsRetur
                .Tables.Add(dtRetur)
                .Tables(0).Columns.Add(urut)
                .Tables(0).Columns.Add(nama_barang)
                .Tables(0).Columns.Add(hrgppn)
                .Tables(0).Columns.Add(jmlretpkt)
                .Tables(0).Columns.Add(jmlretnpkt)
                .Tables(0).Columns.Add(totalqty)
                .Tables(0).Columns.Add(nmsatuan)
                .Tables(0).Columns.Add(jmlhrgpkt)
                .Tables(0).Columns.Add(jmlhrgnpkt)
                .Tables(0).Columns.Add(jmlhrgret)
                .Tables(0).Columns.Add(dijamin)
                .Tables(0).Columns.Add(iurpasien)
                .Tables(0).Columns.Add(kdkasir)
                .Tables(0).Columns.Add(nmkasir)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(notaretur)
                .Tables(0).Columns.Add(no_reg)
                .Tables(0).Columns.Add(no_rm)
                .Tables(0).Columns.Add(nmpasien)
                .Tables(0).Columns.Add(umurthn)
                .Tables(0).Columns.Add(umurbln)
                .Tables(0).Columns.Add(kd_penjamin)
                .Tables(0).Columns.Add(nm_penjamin)
                .Tables(0).Columns.Add(noid)
                .Tables(0).Columns.Add(kd_barang)
                .Tables(0).Columns.Add(idx_barang)
                .Tables(0).Columns.Add(generik)
                .Tables(0).Columns.Add(kd_jns_obat)
                .Tables(0).Columns.Add(kd_gol_obat)
                .Tables(0).Columns.Add(kd_kel_obat)
                .Tables(0).Columns.Add(kdpabrik)
                .Tables(0).Columns.Add(rek_p)
                .Tables(0).Columns.Add(formularium)
                .Tables(0).Columns.Add(tglresep)
                .Tables(0).Columns.Add(notaresep)
                .Tables(0).Columns.Add(kddokter)
                .Tables(0).Columns.Add(nmdokter)
                .Tables(0).Columns.Add(jns_obat)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsRetur
    End Function

    Public Shared Function BuatTabelReturObatInap(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsRetur As DataSet = New DataSet
        Dim dtRetur As DataTable = New DataTable(NamaTabel)
        Dim kdkasir As New DataColumn("kdkasir")
        Dim nmkasir As New DataColumn("nmkasir")
        Dim kdbagian As New DataColumn("kdbagian")
        Dim tanggal As New DataColumn("tanggal")
        Dim notaretur As New DataColumn("notaretur")
        Dim no_reg As New DataColumn("no_reg")
        Dim no_rm As New DataColumn("no_rm")
        Dim nmpasien As New DataColumn("nmpasien")
        Dim umurthn As New DataColumn("umurthn")
        Dim umurbln As New DataColumn("umurbln")
        Dim kd_penjamin As New DataColumn("kd_penjamin")
        Dim nm_penjamin As New DataColumn("nm_penjamin")
        Dim urut As New DataColumn("urut")
        Dim noid As New DataColumn("noid")
        Dim kd_barang As New DataColumn("kd_barang")
        Dim idx_barang As New DataColumn("idx_barang")
        Dim nama_barang As New DataColumn("nama_barang")
        Dim generik As New DataColumn("generik")
        Dim kd_jns_obat As New DataColumn("kd_jns_obat")
        Dim kd_gol_obat As New DataColumn("kd_gol_obat")
        Dim kd_kel_obat As New DataColumn("kd_kel_obat")
        Dim kdpabrik As New DataColumn("kdpabrik")
        Dim rek_p As New DataColumn("rek_p")
        Dim formularium As New DataColumn("formularium")
        Dim tglresep As New DataColumn("tglresep")
        Dim notaresep As New DataColumn("notaresep")
        Dim kddokter As New DataColumn("kddokter")
        Dim nmdokter As New DataColumn("nmdokter")
        Dim hrgppn As New DataColumn("hrgppn")
        Dim jmlretpkt As New DataColumn("jmlretpkt")
        Dim jmlretnpkt As New DataColumn("jmlretnpkt")
        Dim totalqty As New DataColumn("totalqty")
        Dim nmsatuan As New DataColumn("nmsatuan")
        Dim jmlhrgpkt As New DataColumn("jmlhrgpkt")
        Dim jmlhrgnpkt As New DataColumn("jmlhrgnpkt")
        Dim jmlhrgret As New DataColumn("jmlhrgret")
        Dim dijamin As New DataColumn("dijamin")
        Dim iurpasien As New DataColumn("iurpasien")
        Dim jns_obat As New DataColumn("jns_obat")

        Try
            kdkasir.DataType = GetType(String)
            nmkasir.DataType = GetType(String)
            kdbagian.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            notaretur.DataType = GetType(String)
            no_reg.DataType = GetType(String)
            no_rm.DataType = GetType(String)
            nmpasien.DataType = GetType(String)
            umurthn.DataType = GetType(Integer)
            umurbln.DataType = GetType(Integer)
            kd_penjamin.DataType = GetType(String)
            nm_penjamin.DataType = GetType(String)
            urut.DataType = GetType(Integer)
            noid.DataType = GetType(Integer)
            kd_barang.DataType = GetType(String)
            idx_barang.DataType = GetType(Integer)
            nama_barang.DataType = GetType(String)
            generik.DataType = GetType(String)
            kd_jns_obat.DataType = GetType(Integer)
            kd_gol_obat.DataType = GetType(Integer)
            kd_kel_obat.DataType = GetType(Integer)
            kdpabrik.DataType = GetType(String)
            rek_p.DataType = GetType(String)
            formularium.DataType = GetType(String)
            tglresep.DataType = GetType(DateTime)
            notaresep.DataType = GetType(String)
            kddokter.DataType = GetType(String)
            nmdokter.DataType = GetType(String)
            hrgppn.DataType = GetType(Decimal)
            jmlretpkt.DataType = GetType(Decimal)
            jmlretnpkt.DataType = GetType(Decimal)
            totalqty.DataType = GetType(Decimal)
            nmsatuan.DataType = GetType(String)
            jmlhrgpkt.DataType = GetType(Decimal)
            jmlhrgnpkt.DataType = GetType(Decimal)
            jmlhrgret.DataType = GetType(Decimal)
            dijamin.DataType = GetType(Decimal)
            iurpasien.DataType = GetType(Decimal)
            jns_obat.DataType = GetType(String)
            With dsRetur
                .Tables.Add(dtRetur)
                .Tables(0).Columns.Add(urut)
                .Tables(0).Columns.Add(nama_barang)
                .Tables(0).Columns.Add(hrgppn)
                .Tables(0).Columns.Add(jmlretpkt)
                .Tables(0).Columns.Add(jmlretnpkt)
                .Tables(0).Columns.Add(totalqty)
                .Tables(0).Columns.Add(nmsatuan)
                .Tables(0).Columns.Add(jmlhrgpkt)
                .Tables(0).Columns.Add(jmlhrgnpkt)
                .Tables(0).Columns.Add(jmlhrgret)
                .Tables(0).Columns.Add(dijamin)
                .Tables(0).Columns.Add(iurpasien)
                .Tables(0).Columns.Add(kdkasir)
                .Tables(0).Columns.Add(nmkasir)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(notaretur)
                .Tables(0).Columns.Add(no_reg)
                .Tables(0).Columns.Add(no_rm)
                .Tables(0).Columns.Add(nmpasien)
                .Tables(0).Columns.Add(umurthn)
                .Tables(0).Columns.Add(umurbln)
                .Tables(0).Columns.Add(kd_penjamin)
                .Tables(0).Columns.Add(nm_penjamin)
                .Tables(0).Columns.Add(noid)
                .Tables(0).Columns.Add(kd_barang)
                .Tables(0).Columns.Add(idx_barang)
                .Tables(0).Columns.Add(generik)
                .Tables(0).Columns.Add(kd_jns_obat)
                .Tables(0).Columns.Add(kd_gol_obat)
                .Tables(0).Columns.Add(kd_kel_obat)
                .Tables(0).Columns.Add(kdpabrik)
                .Tables(0).Columns.Add(rek_p)
                .Tables(0).Columns.Add(formularium)
                .Tables(0).Columns.Add(tglresep)
                .Tables(0).Columns.Add(notaresep)
                .Tables(0).Columns.Add(kddokter)
                .Tables(0).Columns.Add(nmdokter)
                .Tables(0).Columns.Add(jns_obat)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsRetur
    End Function

    Public Shared Function BuatTabelPermintaanBarangGudang(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsPermintaanBarang As DataSet = New DataSet
        Dim dtPermintaanBarang As DataTable = New DataTable(NamaTabel)
        Dim tanggal As New DataColumn("tanggal")
        Dim nota As New DataColumn("nota")
        Dim nomer As New DataColumn("nomer")
        Dim kdkasir As New DataColumn("kdkasir")
        Dim nmkasir As New DataColumn("nmkasir")
        Dim kdbagian As New DataColumn("kdbagian")
        Dim nmbagian As New DataColumn("nmbagian")
        Dim nama As New DataColumn("nama")
        Dim idbarang As New DataColumn("idbarang")
        Dim kdbarang As New DataColumn("kdbarang")
        Dim nmbarang As New DataColumn("nmbarang")
        Dim kdjenis As New DataColumn("kdjenis")
        Dim jml As New DataColumn("jml")
        Dim nmsatuan As New DataColumn("nmsatuan")
        Dim harga As New DataColumn("harga")
        Dim jmlharga As New DataColumn("jmlharga")
        Dim tglexp As New DataColumn("tglexp")
        Dim nobatch As New DataColumn("nobatch")
        Dim jmlstok As New DataColumn("jmlstok")
        Dim senpot As New DataColumn("senpot")
        Dim posting As New DataColumn("posting")

        Try
            tanggal.DataType = GetType(DateTime)
            nota.DataType = GetType(String)
            nomer.DataType = GetType(Integer)
            kdkasir.DataType = GetType(String)
            nmkasir.DataType = GetType(String)
            kdbagian.DataType = GetType(String)
            nmbagian.DataType = GetType(String)
            nama.DataType = GetType(String)
            idbarang.DataType = GetType(String)
            kdbarang.DataType = GetType(String)
            nmbarang.DataType = GetType(String)
            kdjenis.DataType = GetType(Integer)
            jml.DataType = GetType(Integer)
            nmsatuan.DataType = GetType(String)
            harga.DataType = GetType(Integer)
            jmlharga.DataType = GetType(Integer)
            tglexp.DataType = GetType(DateTime)
            nobatch.DataType = GetType(String)
            jmlstok.DataType = GetType(Integer)
            senpot.DataType = GetType(Integer)
            posting.DataType = GetType(String)
            With dsPermintaanBarang
                .Tables.Add(dtPermintaanBarang)
                .Tables(0).Columns.Add(nomer)
                .Tables(0).Columns.Add(kdbarang)
                .Tables(0).Columns.Add(nmbarang)
                .Tables(0).Columns.Add(harga)
                .Tables(0).Columns.Add(jml)
                .Tables(0).Columns.Add(nmsatuan)
                .Tables(0).Columns.Add(jmlharga)
                .Tables(0).Columns.Add(tglexp)
                .Tables(0).Columns.Add(nobatch)
                .Tables(0).Columns.Add(idbarang)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(nota)
                .Tables(0).Columns.Add(kdkasir)
                .Tables(0).Columns.Add(nmkasir)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(nmbagian)
                .Tables(0).Columns.Add(nama)
                .Tables(0).Columns.Add(kdjenis)
                .Tables(0).Columns.Add(jmlstok)
                .Tables(0).Columns.Add(senpot)
                .Tables(0).Columns.Add(posting)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsPermintaanBarang
    End Function

    Public Shared Function BuatTabelMutasiUnit(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsMutasi As DataSet = New DataSet
        Dim dtMutasi As DataTable = New DataTable(NamaTabel)
        Dim kdbagian As New DataColumn("kdbagian")
        Dim kdkasir As New DataColumn("kdkasir")
        Dim nmkasir As New DataColumn("nmkasir")
        Dim tanggal As New DataColumn("tanggal")
        Dim nota As New DataColumn("nota")
        Dim nomer As New DataColumn("nomer")
        Dim kdbagian1 As New DataColumn("kdbagian1")
        Dim nmbagian1 As New DataColumn("nmbagian1")
        Dim kdbagian2 As New DataColumn("kdbagian2")
        Dim nmbagian2 As New DataColumn("nmbagian2")
        Dim kd_barang As New DataColumn("kd_barang")
        Dim idx_barang As New DataColumn("idx_barang")
        Dim nama_barang As New DataColumn("nama_barang")
        Dim harga As New DataColumn("harga")
        Dim jml As New DataColumn("jml")
        Dim nmsatuan As New DataColumn("nmsatuan")
        Dim jmlharga As New DataColumn("jmlharga")
        Dim posting As New DataColumn("posting")
        Try
            kdbagian.DataType = GetType(String)
            kdkasir.DataType = GetType(String)
            nmkasir.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            nota.DataType = GetType(String)
            nomer.DataType = GetType(Integer)
            nomer.AutoIncrement = True
            nomer.AutoIncrementSeed = 1
            kdbagian1.DataType = GetType(String)
            nmbagian1.DataType = GetType(String)
            kdbagian2.DataType = GetType(String)
            nmbagian2.DataType = GetType(String)
            kd_barang.DataType = GetType(String)
            idx_barang.DataType = GetType(String)
            nama_barang.DataType = GetType(String)
            harga.DataType = GetType(Integer)
            jml.DataType = GetType(Integer)
            nmsatuan.DataType = GetType(String)
            jmlharga.DataType = GetType(Integer)
            posting.DataType = GetType(String)
            With dsMutasi
                .Tables.Add(dtMutasi)
                .Tables(0).Columns.Add(nomer)
                .Tables(0).Columns.Add(kd_barang)
                .Tables(0).Columns.Add(nama_barang)
                .Tables(0).Columns.Add(harga)
                .Tables(0).Columns.Add(jml)
                .Tables(0).Columns.Add(nmsatuan)
                .Tables(0).Columns.Add(jmlharga)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(kdkasir)
                .Tables(0).Columns.Add(nmkasir)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(nota)
                .Tables(0).Columns.Add(kdbagian1)
                .Tables(0).Columns.Add(nmbagian1)
                .Tables(0).Columns.Add(kdbagian2)
                .Tables(0).Columns.Add(nmbagian2)
                .Tables(0).Columns.Add(idx_barang)
                .Tables(0).Columns.Add(posting)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsMutasi
    End Function

    Public Shared Function BuatTabelStokPerbulan(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsStok As DataSet = New DataSet
        Dim dtStok As DataTable = New DataTable(NamaTabel)
        Dim kdbarang As New DataColumn("kdbarang")
        Dim nmbarang As New DataColumn("nmbarang")
        Dim harga As New DataColumn("harga")
        Dim nmsatuan As New DataColumn("nmsatuan")
        Dim kdjenis As New DataColumn("kdjenis")
        Dim nmjenis As New DataColumn("nmjenis")
        Dim stokawal As New DataColumn("stokawal")
        Dim terimagdg As New DataColumn("terimagdg")
        Dim terima1 As New DataColumn("terima1")
        Dim terima2 As New DataColumn("terima2")
        Dim terima3 As New DataColumn("terima3")
        Dim terima4 As New DataColumn("terima4")
        Dim terima5 As New DataColumn("terima5")
        Dim terima6 As New DataColumn("terima6")
        Dim terima7 As New DataColumn("terima7")
        Dim terimaunt As New DataColumn("terimaunt")
        Dim retcekout As New DataColumn("retcekout")
        Dim retinap As New DataColumn("retinap")
        Dim kormasuk As New DataColumn("kormasuk")
        Dim ttlmasuk As New DataColumn("ttlmasuk")
        Dim jualresep As New DataColumn("jualresep")
        Dim jualbebas As New DataColumn("jualbebas")
        Dim mutasi As New DataColumn("mutasi")
        Dim retgudang As New DataColumn("retgudang")
        Dim korkel As New DataColumn("korkel")
        Dim ttlkeluar As New DataColumn("ttlkeluar")
        Dim jmlstok As New DataColumn("jmlstok")
        Dim jmlharga As New DataColumn("jmlharga")

        Try
            kdbarang.DataType = GetType(String)
            nmbarang.DataType = GetType(String)
            harga.DataType = GetType(Integer)
            nmsatuan.DataType = GetType(String)
            kdjenis.DataType = GetType(String)
            nmjenis.DataType = GetType(String)
            stokawal.DataType = GetType(Integer)
            terimagdg.DataType = GetType(Integer)
            terima1.DataType = GetType(Integer)
            terima2.DataType = GetType(Integer)
            terima3.DataType = GetType(Integer)
            terima4.DataType = GetType(Integer)
            terima5.DataType = GetType(Integer)
            terima6.DataType = GetType(Integer)
            terimaunt.DataType = GetType(Integer)
            retcekout.DataType = GetType(Integer)
            retinap.DataType = GetType(Integer)
            kormasuk.DataType = GetType(Integer)
            ttlmasuk.DataType = GetType(Integer)
            jualresep.DataType = GetType(Decimal)
            jualbebas.DataType = GetType(Decimal)
            mutasi.DataType = GetType(Integer)
            retgudang.DataType = GetType(Integer)
            korkel.DataType = GetType(Integer)
            ttlkeluar.DataType = GetType(Integer)
            jmlstok.DataType = GetType(Integer)
            jmlharga.DataType = GetType(Integer)
            With dsStok
                .Tables.Add(dtStok)
                .Tables(0).Columns.Add(nmjenis)
                .Tables(0).Columns.Add(nmbarang)
                .Tables(0).Columns.Add(stokawal)
                .Tables(0).Columns.Add(terimagdg)
                .Tables(0).Columns.Add(terima1)
                .Tables(0).Columns.Add(terima2)
                .Tables(0).Columns.Add(terima3)
                .Tables(0).Columns.Add(terima4)
                .Tables(0).Columns.Add(terima5)
                .Tables(0).Columns.Add(terima6)
                .Tables(0).Columns.Add(terimaunt)
                .Tables(0).Columns.Add(retcekout)
                .Tables(0).Columns.Add(retinap)
                .Tables(0).Columns.Add(kormasuk)
                .Tables(0).Columns.Add(ttlmasuk)
                .Tables(0).Columns.Add(jualresep)
                .Tables(0).Columns.Add(jualbebas)
                .Tables(0).Columns.Add(mutasi)
                .Tables(0).Columns.Add(retgudang)
                .Tables(0).Columns.Add(korkel)
                .Tables(0).Columns.Add(ttlkeluar)
                .Tables(0).Columns.Add(jmlstok)
                .Tables(0).Columns.Add(nmsatuan)
                .Tables(0).Columns.Add(harga)
                .Tables(0).Columns.Add(jmlharga)
                .Tables(0).Columns.Add(kdbarang)
                .Tables(0).Columns.Add(kdjenis)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsStok
    End Function

    Public Shared Function BuatTabelKartuStok(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsStok As DataSet = New DataSet
        Dim dtStok As DataTable = New DataTable(NamaTabel)
        Dim kdbarang As New DataColumn("kdbarang")
        Dim tanggal As New DataColumn("tanggal")
        Dim nonota As New DataColumn("nonota")
        Dim keterangan As New DataColumn("keterangan")
        Dim masukqty As New DataColumn("masukqty")
        Dim keluarqty As New DataColumn("keluarqty")
        Dim saldo As New DataColumn("saldo")
        
        Try
            kdbarang.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            nonota.DataType = GetType(String)
            keterangan.DataType = GetType(String)
            masukqty.DataType = GetType(Decimal)
            keluarqty.DataType = GetType(Decimal)
            saldo.DataType = GetType(Decimal)
            With dsStok
                .Tables.Add(dtStok)
                .Tables(0).Columns.Add(kdbarang)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(nonota)
                .Tables(0).Columns.Add(keterangan)
                .Tables(0).Columns.Add(masukqty)
                .Tables(0).Columns.Add(keluarqty)
                .Tables(0).Columns.Add(saldo)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsStok
    End Function

    Public Shared Function BuatTabelLaporanHarianJualBebas(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsStok As DataSet = New DataSet
        Dim dtStok As DataTable = New DataTable(NamaTabel)
        Dim kdbagian As New DataColumn("kdbagian")
        Dim petugas As New DataColumn("petugas")
        Dim tanggal As New DataColumn("tanggal")
        Dim nonota As New DataColumn("nonota")
        Dim konsumen As New DataColumn("konsumen")
        Dim nama As New DataColumn("nama")
        Dim kddokter As New DataColumn("kddokter")
        Dim nmdokter As New DataColumn("nmdokter")
        Dim lembar As New DataColumn("lembar")
        Dim racik As New DataColumn("racik")
        Dim totalobt As New DataColumn("totalobt")
        Dim totalhrg As New DataColumn("totalhrg")

        Try
            kdbagian.DataType = GetType(String)
            petugas.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            nonota.DataType = GetType(String)
            konsumen.DataType = GetType(String)
            nama.DataType = GetType(String)
            kddokter.DataType = GetType(String)
            nmdokter.DataType = GetType(String)
            lembar.DataType = GetType(Decimal)
            racik.DataType = GetType(Decimal)
            totalobt.DataType = GetType(Decimal)
            totalhrg.DataType = GetType(Decimal)
            With dsStok
                .Tables.Add(dtStok)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(petugas)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(nonota)
                .Tables(0).Columns.Add(konsumen)
                .Tables(0).Columns.Add(nama)
                .Tables(0).Columns.Add(kddokter)
                .Tables(0).Columns.Add(nmdokter)
                .Tables(0).Columns.Add(lembar)
                .Tables(0).Columns.Add(racik)
                .Tables(0).Columns.Add(totalobt)
                .Tables(0).Columns.Add(totalhrg)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsStok
    End Function

    Public Shared Function BuatTabelLaporanHarianJualResep(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsStok As DataSet = New DataSet
        Dim dtStok As DataTable = New DataTable(NamaTabel)
        Dim kdbagian As New DataColumn("kdbagian")
        Dim stsrawat As New DataColumn("stsrawat")
        Dim kdpetugas As New DataColumn("kdpetugas")
        Dim petugas As New DataColumn("petugas")
        Dim tanggal As New DataColumn("tanggal")
        Dim notaresep As New DataColumn("notaresep")
        Dim no_rm As New DataColumn("no_rm")
        Dim nmpasien As New DataColumn("nmpasien")
        Dim kddokter As New DataColumn("kddokter")
        Dim nmdokter As New DataColumn("nmdokter")
        Dim kdsubunit As New DataColumn("kdsubunit")
        Dim nmsubunit As New DataColumn("nmsubunit")
        Dim lembar As New DataColumn("lembar")
        Dim racik As New DataColumn("racik")
        Dim item As New DataColumn("item")
        Dim totalobt As New DataColumn("totalobt")
        Dim totalhrg As New DataColumn("totalhrg")
        Dim kdpenjamin As New DataColumn("kdpenjamin")
        Dim nmpenjamin As New DataColumn("nmpenjamin")
        Try
            kdbagian.DataType = GetType(String)
            stsrawat.DataType = GetType(String)
            kdpetugas.DataType = GetType(String)
            petugas.DataType = GetType(String)
            tanggal.DataType = GetType(DateTime)
            notaresep.DataType = GetType(String)
            no_rm.DataType = GetType(String)
            nmpasien.DataType = GetType(String)
            kddokter.DataType = GetType(String)
            nmdokter.DataType = GetType(String)
            kdsubunit.DataType = GetType(String)
            nmsubunit.DataType = GetType(String)
            lembar.DataType = GetType(Decimal)
            racik.DataType = GetType(Decimal)
            item.DataType = GetType(Decimal)
            totalobt.DataType = GetType(Decimal)
            totalhrg.DataType = GetType(Decimal)
            kdpenjamin.DataType = GetType(String)
            nmpenjamin.DataType = GetType(String)
            With dsStok
                .Tables.Add(dtStok)
                .Tables(0).Columns.Add(kdbagian)
                .Tables(0).Columns.Add(stsrawat)
                .Tables(0).Columns.Add(kdpetugas)
                .Tables(0).Columns.Add(petugas)
                .Tables(0).Columns.Add(tanggal)
                .Tables(0).Columns.Add(notaresep)
                .Tables(0).Columns.Add(no_rm)
                .Tables(0).Columns.Add(nmpasien)
                .Tables(0).Columns.Add(kddokter)
                .Tables(0).Columns.Add(nmdokter)
                .Tables(0).Columns.Add(kdsubunit)
                .Tables(0).Columns.Add(nmsubunit)
                .Tables(0).Columns.Add(lembar)
                .Tables(0).Columns.Add(racik)
                .Tables(0).Columns.Add(item)
                .Tables(0).Columns.Add(totalobt)
                .Tables(0).Columns.Add(totalhrg)
                .Tables(0).Columns.Add(kdpenjamin)
                .Tables(0).Columns.Add(nmpenjamin)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsStok
    End Function

    Public Shared Function BuatTabelEtiketModel4(Optional ByVal NamaTabel As String = "Table1") As DataSet
        Dim dsStok As DataSet = New DataSet
        Dim dtStok As DataTable = New DataTable(NamaTabel)
        Dim namaObat As New DataColumn("namaObat")
        Dim waktuMinum As New DataColumn("waktuMinum")
        Dim ketMinum As New DataColumn("ketMinum")
        'Dim jenisObat As New DataColumn("jenisObat")
        Dim tglExp As New DataColumn("tglExp")
        Try
            namaObat.DataType = GetType(String)
            waktuMinum.DataType = GetType(String)
            ketMinum.DataType = GetType(String)
            'jenisObat.DataType = GetType(String)
            tglExp.DataType = GetType(String)
            With dsStok
                .Tables.Add(dtStok)
                .Tables(0).Columns.Add(namaObat)
                .Tables(0).Columns.Add(waktuMinum)
                .Tables(0).Columns.Add(ketMinum)
                '.Tables(0).Columns.Add(jenisObat)
                .Tables(0).Columns.Add(tglExp)
            End With
        Catch ex As Exception
            MessageBox.Show(ex.Message, "ExecuteQuery")
        End Try
        Return dsStok
    End Function

End Class
