Imports Syncfusion.Windows.Forms
Imports Syncfusion.Windows.Forms.Tools

Public Class FormCetakStok
    Inherits Office2010Form

   
    Private Sub FormCetakStok_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Try
            'mendeklarasikan sebuah dataset...
            'beri nama datasetnya, yaitu "dataset - latihan"...
            Using a As New DataSet("DataSetStok")
                'mendeklarasikan sebuah tabel...
                'beri nama tabelnya, yaitu "biodata"...
                Using b As New DataTable("stokbarang")
                    'buat kolom pertama, yaitu id...
                    b.Columns.Add("nmbarang", GetType(String))
                    'buat kolom kedua, yaitu nama lengkap...
                    b.Columns.Add("stokawal", GetType(Integer))
                    'simpan tabel biodata ini kedalam dataset...
                    a.Tables.Add(b)
                End Using 'tabel biodata telah ditutup dan dihapus dari memory...

                'sekarang bakukan dataset ini kedalam sebuah file...
                'filenya akan disimpan di desktop, dengan nama "dataset - latihan.xml"...
                'dan jangan lupa, jenis skemanya adalah xmlwriteschema, yaitu file akan ditulis secara lengkap...
                a.WriteXml(Application.StartupPath & "\Report\stokbarang.xml", XmlWriteMode.WriteSchema)
            End Using 'dataset telah ditutup dan dihapus dari memory...
        Catch ex As Exception
        End Try
    End Sub
End Class